create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  url_hash text not null unique,
  url text,
  title text not null,
  source text,
  published_at timestamptz,
  fetched_at timestamptz default now(),
  tickers text[] default '{}',
  summary text,
  news_type text,
  urgency_score integer default 0 check (urgency_score between 0 and 100),
  urgency_level text,
  impact text,
  market_scope text,
  reasons text[] default '{}',
  email_sent boolean default false,
  email_sent_at timestamptz
);

create index if not exists idx_articles_published_at on public.articles (published_at desc);
create index if not exists idx_articles_urgency on public.articles (urgency_score desc);
create index if not exists idx_articles_unsent on public.articles (email_sent, urgency_score desc);

create table if not exists public.subscribers (
  email text primary key,
  enabled boolean default true,
  urgency_threshold integer default 70 check (urgency_threshold between 0 and 100),
  created_at timestamptz default now()
);

create table if not exists public.article_deliveries (
  article_id bigint not null references public.articles(id) on delete cascade,
  email text not null,
  sent_at timestamptz default now(),
  primary key (article_id, email)
);
create index if not exists idx_deliveries_email on public.article_deliveries (email, sent_at desc);

-- V5 accesses these tables only from trusted server-side secrets / GitHub Actions.
-- Do not expose the service-role key in browser-side code.

-- Lock REST access to trusted server-side service-role usage.
alter table public.articles enable row level security;
alter table public.subscribers enable row level security;
alter table public.article_deliveries enable row level security;
